version: "3.3"

services:
  database:
    image: "postgres"
    container_name: "database"
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "8001:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

