// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.1
// source: movie.proto

package movie

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MovieApiClient is the client API for MovieApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovieApiClient interface {
	GetMovies(ctx context.Context, in *RequestMovies, opts ...grpc.CallOption) (*ResponseMovies, error)
	GetMovie(ctx context.Context, in *RequestMovies, opts ...grpc.CallOption) (*ResponseMovie, error)
}

type movieApiClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieApiClient(cc grpc.ClientConnInterface) MovieApiClient {
	return &movieApiClient{cc}
}

func (c *movieApiClient) GetMovies(ctx context.Context, in *RequestMovies, opts ...grpc.CallOption) (*ResponseMovies, error) {
	out := new(ResponseMovies)
	err := c.cc.Invoke(ctx, "/MovieApi/GetMovies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieApiClient) GetMovie(ctx context.Context, in *RequestMovies, opts ...grpc.CallOption) (*ResponseMovie, error) {
	out := new(ResponseMovie)
	err := c.cc.Invoke(ctx, "/MovieApi/GetMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieApiServer is the server API for MovieApi service.
// All implementations must embed UnimplementedMovieApiServer
// for forward compatibility
type MovieApiServer interface {
	GetMovies(context.Context, *RequestMovies) (*ResponseMovies, error)
	GetMovie(context.Context, *RequestMovies) (*ResponseMovie, error)
	mustEmbedUnimplementedMovieApiServer()
}

// UnimplementedMovieApiServer must be embedded to have forward compatible implementations.
type UnimplementedMovieApiServer struct {
}

func (UnimplementedMovieApiServer) GetMovies(context.Context, *RequestMovies) (*ResponseMovies, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovies not implemented")
}
func (UnimplementedMovieApiServer) GetMovie(context.Context, *RequestMovies) (*ResponseMovie, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovie not implemented")
}
func (UnimplementedMovieApiServer) mustEmbedUnimplementedMovieApiServer() {}

// UnsafeMovieApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovieApiServer will
// result in compilation errors.
type UnsafeMovieApiServer interface {
	mustEmbedUnimplementedMovieApiServer()
}

func RegisterMovieApiServer(s grpc.ServiceRegistrar, srv MovieApiServer) {
	s.RegisterService(&MovieApi_ServiceDesc, srv)
}

func _MovieApi_GetMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMovies)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieApiServer).GetMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MovieApi/GetMovies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieApiServer).GetMovies(ctx, req.(*RequestMovies))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieApi_GetMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMovies)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieApiServer).GetMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MovieApi/GetMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieApiServer).GetMovie(ctx, req.(*RequestMovies))
	}
	return interceptor(ctx, in, info, handler)
}

// MovieApi_ServiceDesc is the grpc.ServiceDesc for MovieApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovieApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MovieApi",
	HandlerType: (*MovieApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovies",
			Handler:    _MovieApi_GetMovies_Handler,
		},
		{
			MethodName: "GetMovie",
			Handler:    _MovieApi_GetMovie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movie.proto",
}
